execute_process(COMMAND go env GOPATH OUTPUT_VARIABLE GO_PATH OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND go env GOOS   OUTPUT_VARIABLE GO_OS   OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND go env GOARCH OUTPUT_VARIABLE GO_ARCH OUTPUT_STRIP_TRAILING_WHITESPACE)
set(GO_PKG_DIR ${GO_PATH}/pkg/${GO_OS}_${GO_ARCH})

if(NOT CMAKE_Go_COMPILE_OBJECT)
  set(CMAKE_Go_COMPILE_OBJECT "go tool compile -I ${GO_PKG_DIR} -l -N -o <OBJECT> <SOURCE> ")
endif()

if(NOT CMAKE_Go_LINK_EXECUTABLE)
  set(CMAKE_Go_LINK_EXECUTABLE "go tool link -L ${GO_PKG_DIR} -o <TARGET> <OBJECTS>  ")
endif()

